version: '3'

services:
  mysql:
    image: "mysql:5.7" 
    environment:
      MYSQL_USER: root #必填，不然会创建空密码的root用户
      MYSQL_ROOT_PASSWORD: xxxxxx
      MYSQL_DATABASE: "dev" #默认创建的数据
    ports:
      - '3306:3306' #关联到宿主机的3306端口
    volumes:
      - ./tmp/db:/var/lib/mysql #将contaner数据目录挂在到宿主机的对应目录
  
  redis:
    image: redis
    ports:
      - '6379:6379'
      
  web:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/app
    working_dir: /app
    ports:
      - "3000:3000"
    depends_on:
      - mysql #依赖的service，up web时同时up mysql service
      - redis